# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: bump_development
  encoding: utf8
  username: bump
  password:
  host: localhost
  min_messages: WARNING

production:
  adapter: postgresql
  database: bump_production
  encoding: utf8
  username: bump
  password:
  host: localhost

test:
  adapter: postgresql
  database: bump_test
  encoding: utf8
  username: bump
  password:
  host: localhost
  min_messages: WARNING
